### ISSUE TITLE
Webpacker infinitely compiling with webpack 5.42.0

### ISSUE THREAD

**Issue by drnic** [rails/webpacker#3078]
Currently using `gem "webpacker", "6.0.0.beta.7"`

After bumping my npm deps I found that webpacker was infinitely recompiling my assets:

```
webpack.1 |   asset js/administrate-10058ef4dda95658a6fc.js 27.1 KiB [emitted] [immutable] (name: administrate)
webpack.1 |   asset js/runtime-f5ce4b1044f14a77e0d2.js 13.6 KiB [emitted] [immutable] (name: runtime)
webpack.1 | assets by path css/*.css 154 KiB
webpack.1 |   asset css/application-c10f1359.css 139 KiB [emitted] [immutable] (name: application)
webpack.1 |   asset css/vendors-node_modules_core-js_modules_es_array-buffer_constructor_js-node_modules_core-js_modu-9f7de7-fb9b7bd4.css 15.4 KiB [emitted] [immutable] (id hint: vendors)
webpack.1 | asset manifest.json 3.71 KiB [emitted]
webpack.1 | webpack 5.42.0 compiled successfully in 9294 ms
webpack.1 | ℹ ｢wdm｣: Compiled successfully.
webpack.1 | ℹ ｢wdm｣: Compiling...
webpack.1 | ℹ ｢wdm｣: assets by status 5.16 MiB [cached] 17 assets
webpack.1 | assets by path . 156 KiB
webpack.1 |   asset css/application-0643cd55.css 139 KiB [emitted] [immutable] (name: application)
webpack.1 |   asset js/runtime-39d3fdd6fa6d4174b45c.js 13.6 KiB [emitted] [immutable] (name: runtime)
webpack.1 |   asset manifest.json 3.71 KiB [emitted]
webpack.1 | webpack 5.42.0 compiled successfully in 2149 ms
webpack.1 | ℹ ｢wdm｣: Compiled successfully.
webpack.1 | ℹ ｢wdm｣: Compiling...
webpack.1 | ℹ ｢wdm｣: assets by status 5.31 MiB [cached] 19 assets
webpack.1 | asset manifest.json 3.71 KiB [emitted]
webpack.1 | webpack 5.42.0 compiled successfully in 1334 ms
webpack.1 | ℹ ｢wdm｣: Compiled successfully.
webpack.1 | ℹ ｢wdm｣: Compiling...
webpack.1 | ℹ ｢wdm｣: assets by status 5.31 MiB [cached] 19 assets
webpack.1 | asset manifest.json 3.71 KiB [emitted]
webpack.1 | webpack 5.42.0 compiled successfully in 1442 ms
webpack.1 | ℹ ｢wdm｣: Compiled successfully.
webpack.1 | ℹ ｢wdm｣: Compiling...
```

I isolated the problem down to webpack 5.42.0 specifically. I've found webpacker works with webpack 5.41.0 as expected, but infinite loops on 5.42.0.

For anyone else with this problem and needs a workaround: in my `package.json` I restrict webpack:

```
    "webpack": "5.41.0",
```

But after `yarn` I also manually mutate the `yarn.lock` to prevent `webpacker` from installing `webpack` 5.42.0.

Update: having said that, my combination of webpacker + webpack is failing to deploy to heroku:

```
       Compiling...
       Compilation failed:
       [webpack-cli] TypeError: The 'compilation' argument must be an instance of Compilation
           at Function.getCompilationHooks (/tmp/build_217bdc4c/node_modules/@rails/webpacker/node_modules/webpack/lib/NormalModule.js:193:10)
           at WebpackAssetsManifest.handleCompilation (/tmp/build_217bdc4c/node_modules/@rails/webpacker/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js:778:18)
           at Hook.eval [as call] (eval at create (/tmp/build_217bdc4c/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:100:1)
           at Hook.CALL_DELEGATE [as _call] (/tmp/build_217bdc4c/node_modules/tapable/lib/Hook.js:14:14)
           at Compiler.newCompilation (/tmp/build_217bdc4c/node_modules/webpack/lib/Compiler.js:1034:26)
           at /tmp/build_217bdc4c/node_modules/webpack/lib/Compiler.js:1076:29
           at Hook.eval [as callAsync] (eval at create (/tmp/build_217bdc4c/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
           at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/tmp/build_217bdc4c/node_modules/tapable/lib/Hook.js:18:14)
           at Compiler.compile (/tmp/build_217bdc4c/node_modules/webpack/lib/Compiler.js:1071:28)
           at /tmp/build_217bdc4c/node_modules/webpack/lib/Compiler.js:498:12
```

I downgraded to 5.40.0 and heroku is happy.

**Comment by kohheepeace** [comment]
I also encountered the error **"The 'compilation' argument must be an instance of Compilation".**

This may be caused by the different versions of `webpack` installed by `@rails/webpacker` and `rails webpacker:install`, [as described in this issue](https://github.com/rails/webpacker/issues/2864#issuecomment-803502849).

In `package.json`, there are `@rails/webpacker` and `webpack`.
```js
{
// ...
	"dependencies": {
// ....
		"@rails/webpacker": "^6.0.0-beta.7",
// ...
		"webpack": "5.38.1",
		"webpack-cli": "4.7.2"
	},
	"version": "0.1.0",
	"devDependencies": {
		"@webpack-cli/serve": "^1.5.1",
		"webpack-dev-server": "^3.11.2"
	},
// ...
}
```

In `terminal`
```sh
$ yarn why webpack
yarn why v1.22.10
...
=> Found "webpack@5.38.1"
...
=> Found "@rails/webpacker#webpack@5.42.1"
...
Done in 1.33s.
```

So, I solved this problem by using `yarn remove webpack`.

`terminal`
```sh
yarn remove webpack
```

Then if you run `yarn why webpack`, You will see that only one webpack version will be displayed.
```sh
$ yarn why webpack
=> Found "webpack@5.42.1"
```

**Comment by frullah** [comment]
i have the same problem, and i found the solution by setting `webpack` version in package.json `resolutions`
```javascript
// ...
"dependencies": {
  // ...
  "webpack": "5.44.0",
  // ...
},
"resolutions": {
  "webpack": "5.44.0"
},
// ...
```

reference:
https://classic.yarnpkg.com/en/docs/selective-version-resolutions

**Comment by drnic** [comment]
Super intriguing. I'm happy the ideas above work for your app. Super strange that no permutation of them stops infinite compilation for my app. I'm assuming there is something else configured oddly in my app. I've deleted `node_modules` and `public/pack`. I tried the ideas above.

Next, I sadly might need to recreate my app piece by piece until the issue appears... or from a new repo it never rears its head again.

**Comment by drnic** [comment]
I recreated my app from JSP `master` piece by piece and never saw the infinite compilation issue again. I'll close this ticket as unreproducible.

**Comment by drnic** [comment]
The issue has been diagnosed. My tailwind.config.js purge paths were the root cause.

I previously had:

```js
  // Purge unused TailwindCSS styles
  purge: {
    enabled: ["production", "staging"].includes(process.env.NODE_ENV),
    content: [
      "./**/*.html.erb",
      "./app/helpers/**/*.rb",
      "./app/javascript/**/*.js"
    ]
  },
```

And now have

```js
  // Purge unused TailwindCSS styles
  purge: {
    enabled: ["production", "staging"].includes(process.env.NODE_ENV),
    content: [
      "./app/helpers/**/*.rb",
      "./app/javascript/**/*.js",
      "./app/components/**/*.erb",
      "./app/views/**/*.erb"
    ]
  },
```
