### ISSUE TITLE
ERB support not woking in a bare bones application

### ISSUE THREAD

**Issue by juandefelix** [rails/webpacker#1454]
Hi,
I'm working on a Rails 5.2 application with Webpacker 3.4.3. I am trying to include images from the assets pipeline in my javascript code and I understand that for that purpose, I should add ERB support to webpack. I was having issues adding the ERB support, by running `bundle exec rails webpacker:install:erb`. I even tried this command in a fresh new application, in order to rule out other possible issues.

After running the command, I see the new loader, the updated webpack configuration, and the `hello_erb.js.erb` file in the `app/javascripts/packs` folder. When I run `./bin/webpack-dev-server`, i receive the following errors:
```
 12% building modules 20/23 modules 3 active ...-test/node_modules/ansi-html/index.jsRunning via Spring preloader in process 2060
 13% building modules 25/27 modules 2 active ...s/html-entities/lib/html5-entities.js(erb):1:in `<main>': undefined method `javascript_pack_tag' for main:Object (NoMethodError)
```
later in the logs:
```
ERROR in ./app/javascript/packs/hello_erb.js.erb
Module build failed: Error: rails-erb-loader failed with code: 1
    at ChildProcess.<anonymous> (/Users/juanfortiz/Desktop/antybuddy/webpacker-test/node_modules/rails-erb-loader/index.js:108:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
 @ multi (webpack)-dev-server/client?http://localhost:3035 ./app/javascript/packs/hello_erb.js.erb
webpack: Failed to compile.
```
Any help with this issue, please?

**Comment by ytbryan** [comment]
can you share your repo?

**Comment by juandefelix** [comment]
Sure, [https://github.com/juandefelix/webpacker-test](https://github.com/juandefelix/webpacker-test)
