### PR TITLE
Backport #3250 to 5-x-stable branch

### LINKED ISSUE #3299: Incompatibility with Ruby 3.2.0
Ruby version: 3.2.0
Rails version: 6.1.7
Webpacker version: 5.4.3

Expected behavior:
When I run `rails webpacker:install` (or `rails new appname` which runs the preceding command), it should do all the webpacker installation.
Actual behavior:
It gives an error
```
rails aborted!
NoMethodError: undefined method `exists?' for Dir:Class
~/rails6testapp/gemfile-review/bin/rails:5:in `<top (required)>'
~/rails6testapp/gemfile-review/bin/spring:10:in `require'
~/rails6testapp/gemfile-review/bin/spring:10:in `block in <top (required)>'
~s/rails6testapp/gemfile-review/bin/spring:7:in `<top (required)>'
```
See https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/
Small, reproducible repo:
set .ruby-version to 3.2.0, make a new gemset in .ruby-gemset, and generate a new rails app (making sure to use Rails 6, maybe this is fixed in Rails 7).

### PR DESCRIPTION
**Pull request by amatsuda**
Currently released stable version of webpacker (5.4.3) does not work on the newest stable Ruby (3.2.0) because webpacker 5.4.3 includes `Dir.exists?` and `File.exists?` that were removed in Ruby 3.2.

Hence, the current situation is that Rails 6.1 users cannot upgrade to Ruby 3.2 because there's no webpacker that supports that versions stack. We could solve this situation by backporting a single commit from #3250.

Please consider merging this and cutting the version 5.4.4 release from 5-x-stable branch. Then probably people would stop complaining to the Ruby-core on the Ruby BTS about this error from webpacker... https://bugs.ruby-lang.org/issues/19352

Closes #3299

### CODE REVIEW

**Comment by dlupu** [comment]
💯 would appreciate this to be done soon.

**Comment by dlupu** [comment]
@byroot, thanks for backporting this and releasing version 5.4.4. Any chance you can do something about https://github.com/rails/webpacker/issues/3308 ?

**Comment by byroot** [comment]
Thanks for letting me know. Unfortunately I don't have an NPM account, hence not the ownership of the package. I relayed the issue to rails-core.

**Comment by byroot** [comment]
@dhh released the 5.4.4 a few minutes ago: https://www.npmjs.com/package/@rails/webpacker so you should be good now.
