### ISSUE TITLE
Unable to load images after upgrading to v6.0.0.beta7

### ISSUE THREAD

**Issue by sujaysudheenda** [rails/webpacker#3093]
I am unable to get the images working on latest release of webpacker
version: 6.0.0.beta7
rails: 6.0.3.1

I recently upgraded from v5 webpacker to v6. everything seems to load but I see this error for images:
```
fromRequireContextWithGlobalFallback.js:19 Error: Cannot find module '../images/logoWhite'
    at webpackMissingModule
```

error in terminal (bin/webpack-dev-server)
```
Module not found: Error: Can't resolve '../images/logoWhite' in

```

How am I importing images?
I am running a react app so my imports look like this:
```
import logoWhite from '../images/logoWhite';

```

How does my webpacker config look?
```
const { webpackConfig } = require("@rails/webpacker");
const { merge } = require("webpack-merge");

const customConfig = {
  resolve: {
    extensions: [".css", ".scss"],
  },
};
webpackConfig.module.rules.map((module) => {
  // lets iterate Rules...
  if (module.test && module.test.toString().includes("scss")) {
    // scss and sass are in same bag.
    // We need SCSS Rule. Now splice it with `resolve-url-loader`
    module.use.splice(-1, 0, {
      loader: require.resolve("resolve-url-loader"),
    });
  }
  return module;
});

module.exports = merge(webpackConfig, customConfig);
```
what loaders have I installed?
```
sass-loader, resolve-url-loader, file-loader, css-loader
```
I have the following in application.js
```
const images = require.context('../images', true)
const imagePath = (name) => images(name, true)
```

show me your webpack.yml
```
default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  webpack_compile_output: true

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: ['app/javascript/images']

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  static_assets_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2

  extensions:
    - .jsx
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg
  
development:
  <<: *default
  compile: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    # Inject browserside javascript that required by both HMR and Live(full) reload
    inject_client: true
    # Hot Module Replacement updates modules while the application is running without a full reload
    hmr: false
    # Inline should be set to true if using HMR; it inserts a script to take care of live reloading
    inline: true
    # Should we show a full-screen overlay in the browser when there are compiler errors or warnings?
    overlay: true
    # Should we use gzip compression?
    compress: true
    # Note that apps that do not check the host are vulnerable to DNS rebinding attacks
    disable_host_check: true
    # This option lets the browser open with your local IP
    use_local_ip: false
    # When enabled, nothing except the initial startup information will be written to the console.
    # This also means that errors or warnings from webpack are not visible.
    quiet: false
    pretty: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'
````

What am I missing?
I tried few solutions online and few things recommended in issues in this project, nothing seems to work

**Comment by mcmire** [comment]
Have you tried adding the extension to the end of the path you're importing? Webpack isn't able to guess which type of file you want to bring in.

**Comment by sujaysudheenda** [comment]
that was it! thanks, @mcmire. I should have noticed that difference in that particular file when compared to others where we have actually specified the extension. 

somehow it worked in v5.x versions.


One follow-up question, Do I still need the setup for `resolve-url-loader` that I have in webpack/base.js? 
(disclaimer: I am not proficient in webpacker configs)

**Comment by mcmire** [comment]
@sujaysudheenda Yeah, if you were using `resolve-url-loader` before I believe you would still need to use it. I haven't found any evidence that the problem it solves has been fixed or even addressed in `sass-loader`.

**Comment by Eusebius1920** [comment]
Off-topic / unrelated: 
Also review your `webpacker.yml`. As far as I know the `extensions` and `static_assets_extensions` are removed with webpacker v6. (see: https://github.com/rails/webpacker/blob/v6.0.0.beta.7/lib/install/config/webpacker.yml)

**Comment by wwahammy** [comment]
@sujaysudheenda: has this issue been solved? If so, would you be able to close this issue?
