### ISSUE TITLE
No such file or directory node_modules/.bin/webpack

### ISSUE THREAD

**Issue by kortirso** [rails/webpacker#1035]
Hi, I have simple rails 5.1.4 app, I'm adding webpacker 3.0.2, installed it with react support, then run deploy with capistrano and get this error
No such file or directory - /var/www/html/slings/releases/20171124115730/node_modules/.bin/webpack (Errno::ENOENT)
What should I need to do more to configure webpack?

**Comment by gauravtiwari** [comment]
@kortirso Is yarn install being run when deploying your app? What version of yarn are you using? This should all be covered by `assets:precompile` task. Could you post full stack-trace please?

**Comment by kortirso** [comment]
With webpacker 2.0 everything is compiled normally.
Local yarn is 1.2.1, server - 1.0.1

last logs from failed deploy are
`deploy:assets:precompile
~/.rvm/bin/rvm default do bundle exec rake assets:precompile
Webpacker is installed
Using /var/www/html/slings/releases/20171124115730/config/webpacker.yml file for setting up webpack paths
Compiling…
Compilation failed:
/var/www/html/slings/shared/bundle/ruby/2.3.0/gems/webpacker-3.0.2/lib/webpacker/webpack_runner.rb:11:in exec: No such file or directory`

I didn't see in logs that `yarn install` being run

**Comment by gauravtiwari** [comment]
Could you add an extra command in your deployment? `yarn install` before assets:precompile please and see what happens.

**Comment by kortirso** [comment]
I deleted previous version, reinstall 3.0.2, added `yarn install` task before `deploy:assets:precompile`, removed a few js libraries - and I have got successful deploy

**Comment by kortirso** [comment]
I don't know what really happens, now it's working, thanks and sorry for spended time

**Comment by gauravtiwari** [comment]
Great 👍

**Comment by scottrobertson** [comment]
We are seeing this after upgrading from 3.0.2 to 3.2.1

```
yarn install v1.3.2
warning package.json: No license field
warning No license field
[1/5] 🔍  Resolving packages...
[2/5] 🚚  Fetching packages...
[3/5] 🔗  Linking dependencies...
warning "@rails/webpacker > postcss-cssnext@3.1.0" has unmet peer dependency "caniuse-lite@^1.0.30000697".
warning " > vue-loader@14.0.2" has unmet peer dependency "css-loader@*".
warning " > webpack-dev-server@2.11.1" has unmet peer dependency "webpack@^2.2.0 || ^3.0.0".
warning "webpack-dev-server > webpack-dev-middleware@1.12.2" has unmet peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0".
[4/5] 📃  Building fresh packages...
[5/5] ♻️  Cleaning modules...
✨  Done in 4.57s.
Webpacker is installed 🎉 🍰
Using config/webpacker.yml file for setting up webpack paths
Compiling…
Compilation failed:

/gems/webpacker-3.2.1/lib/webpacker/webpack_runner.rb:11:in `exec': No such file or directory - node_modules/.bin/webpack (Errno::ENOENT)
	from /gems/webpacker-3.2.1/lib/webpacker/webpack_runner.rb:11:in `block in run'
	from /gems/webpacker-3.2.1/lib/webpacker/webpack_runner.rb:10:in `chdir'
	from /gems/webpacker-3.2.1/lib/webpacker/webpack_runner.rb:10:in `run'
	from /gems/webpacker-3.2.1/lib/webpacker/runner.rb:6:in `run'
	from /gems/webpacker-3.2.1/exe/webpack:8:in `<top (required)>'
	from /bin/webpack:22:in `load'
	from /bin/webpack:22:in `<main>'
	from /bin/ruby_executable_hooks:15:in `eval'
	from /bin/ruby_executable_hooks:15:in `<main>'
```
