### PR TITLE
Gracefully handle missing node

### PR DESCRIPTION
**Pull request by brasic**
The `webpacker:check_node` task blows up when node is not installed.  The code that rescues `Errno::ENOENT` doesn't behave as expected when rails is loaded because [ActiveSupport monkeypatches Kernel#`]( https://github.com/rails/rails/blob/7d75599c875b081f63fc292e454b25e8e42eb60e/activesupport/lib/active_support/core_ext/kernel/agnostics.rb) to suppress raising Errno::ENOENT.  With this monkeypatch in place the code never reaches the fallback branch for legacy node versions introduced in https://github.com/rails/webpacker/pull/798.

We can fix this by manually raising the exception that the activesupport monkeypatch has suppressed.

Before:
```
$ bundle exec rake webpacker:check_node
[...]/gems/ruby-2.4.2/bin/rake: No such file or directory - node
rake aborted!
NoMethodError: undefined method `strip' for nil:NilClass
[...]/gems/webpacker-3.1.1/lib/tasks/webpacker/check_node.rake:16:in `block (2 levels) in <main>'
```

After:
```
$ bundle exec rake webpacker:check_node
[...]/gems/ruby-2.4.2/bin/rake: No such file or directory - node
[...]/gems/ruby-2.4.2/bin/rake: No such file or directory - nodejs
Node.js not installed. Please download and install Node.js https://nodejs.org/en/download/
```

Fixes https://github.com/rails/webpacker/issues/954

### CODE REVIEW

File: lib/tasks/webpacker/check_node.rake [hunk 1]
```diff
@@ -4,6 +4,7 @@ namespace :webpacker do
     begin
       begin
         node_version = `node -v`
+        raise Errno::ENOENT if node_version.blank?
       rescue Errno::ENOENT
         node_version = `nodejs -v`
         raise Errno::ENOENT if node_version.blank?
```
Comment (gauravtiwari) [inline lib/tasks/webpacker/check_node.rake]: How about if we re-raise it outside of rescue then I guess we don't need to raise twice?

Comment (gauravtiwari) [reply lib/tasks/webpacker/check_node.rake]:
```rb
   begin
      node_version = `node -v`
   rescue Errno::ENOENT
      node_version = `nodejs -v`
    end

   raise Errno::ENOENT if node_version.blank?
```

Comment (brasic) [reply lib/tasks/webpacker/check_node.rake]: @gauravtiwari that approach would fix the "node not installed" issue but it would still leave the change in #798 nonfunctional since the first block would never raise so the `nodejs` branch would never be tried.

Comment (brasic) [reply lib/tasks/webpacker/check_node.rake]: Part of the issue is that I'm not sure we can depend one way or the other on whether or not the activesupport monkeypatch will be in place.  This approach works whether Kernel#` is monkeypatched or not.

Comment (brasic) [reply lib/tasks/webpacker/check_node.rake]: This simplifies things a lot and works the same whether or not ActiveSupport has monkeypatched Kernel#`: e49d10a0cac36fdb3206802206328418e4fb7f13

Comment (gauravtiwari) [reply lib/tasks/webpacker/check_node.rake]: Awesome 🍰  💯

**Comment by gauravtiwari** [comment]
Thanks @brasic 👍  💯
