### ISSUE TITLE
The migration from resolved_paths to additional_paths is not backwards-compatible

### ISSUE THREAD

**Issue by cmitz** [rails/webpacker#2866]
We originally encountered a nil-pointer when upgrading from `webpacker` 5.1 to 5.2:
```
NoMethodError: undefined method `+' for nil:NilClass
/srv/retail/idcloud_s/shared/bundle/ruby/2.7.0/gems/webpacker-5.2.1/lib/webpacker/configuration.rb:31:in `additional_paths'
```

The fix was renaming `resolved_paths` to `additional_paths`, even though the implementation of `additional_paths` should have been backwards-compatible. The following conversation happened in #2560:

---

@cmitz Yes, in this case, that is a bug and not intended behaviour (my bad). I think a new issue would be worth it 😄 

That is an interesting `nil` issue 🤔 
The `additional_paths` should be falling back to defaults set in the YAML afaiu:
https://github.com/rails/webpacker/blob/3d73dbad1eeaf3ef1b7aeaba4ba9262d507f999e/lib/webpacker/configuration.rb#L30-L32
https://github.com/rails/webpacker/blob/3d73dbad1eeaf3ef1b7aeaba4ba9262d507f999e/lib/webpacker/configuration.rb#L87-L89
https://github.com/rails/webpacker/blob/3d73dbad1eeaf3ef1b7aeaba4ba9262d507f999e/lib/webpacker/configuration.rb#L109-L112
https://github.com/rails/webpacker/blob/3d73dbad1eeaf3ef1b7aeaba4ba9262d507f999e/lib/install/config/webpacker.yml#L11-L13

_Originally posted by @CGA1123 in https://github.com/rails/webpacker/pull/2560#issuecomment-755339943_

**Comment by CGA1123** [comment]
@cmitz Are you able to share a reproducible config which causes this error?

**Comment by cmitz** [comment]
Sorry for forgetting about this. I will take some time this afternoon to try to create an example repo

**Comment by cmitz** [comment]
Sorry about this, but I can't reproduce it in a new Rails app, but also not anymore in my own Rails app. 
In that case it's very obviously some quirk in our own config/application, not a bug in webpacker

**Comment by swanson** [comment]
I ran into this today upgrading as well. In my case I was going from webpacker `4.0.7` to `5.2.1`

Here was my config that failed with (I was deploying to a `staging` environment on Heroku):

```
NoMethodError: undefined method `+' for nil:NilClass
       /tmp/build_3720ddf9_/vendor/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/webpacker/configuration.rb:31:in `additional_paths'
       /tmp/build_3720ddf9_/vendor/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/webpacker/configuration.rb:35:in `additional_paths_globbed'
       /tmp/build_3720ddf9_/vendor/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/webpacker/compiler.rb:93:in `default_watched_paths'
       /tmp/build_3720ddf9_/vendor/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/webpacker/compiler.rb:57:in `watched_files_digest'
       /tmp/build_3720ddf9_/vendor/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/webpacker/compiler.rb:38:in `fresh?'
       /tmp/build_3720ddf9_/vendor/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/webpacker/compiler.rb:43:in `stale?'
       /tmp/build_3720ddf9_/vendor/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/webpacker/compiler.rb:22:in `compile'
       /tmp/build_3720ddf9_/vendor/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/webpacker/commands.rb:51:in `compile'
       /tmp/build_3720ddf9_/vendor/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/webpacker.rb:35:in `compile'
       /tmp/build_3720ddf9_/vendor/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/tasks/webpacker/compile.rake:23:in `block (4 levels) in <main>'
       /tmp/build_3720ddf9_/vendor/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/webpacker.rb:28:in `ensure_log_goes_to_stdout'
       /tmp/build_3720ddf9_/vendor/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/tasks/webpacker/compile.rake:22:in `block (3 levels) in <main>'
       /tmp/build_3720ddf9_/vendor/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/webpacker.rb:20:in `with_node_env'
       /tmp/build_3720ddf9_/vendor/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/tasks/webpacker/compile.rake:21:in `block (2 levels) in <main>'
       /tmp/build_3720ddf9_/vendor/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/tasks/webpacker/compile.rake:14:in `block in enhance_assets_precompile'
       Tasks: TOP => webpacker:compile
```

Here is my full `config/webpacker.yml`

```
# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  public_root_path: public
  source_entry_path: packs
  public_output_path: packs
  cache_path: tmp/cache/webpacker

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  extensions:
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

  extract_css: true

development:
  <<: *default
  compile: true
  webpack_compile_output: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      "Access-Control-Allow-Origin": "*"
    watch_options:
      ignored: /node_modules/

test:
  <<: *default
  compile: true

  # Compile test packs to a separate directory
  public_output_path: packs-test

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true

staging:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true
```

Changing `resolved_paths` to `additional_paths` resolved the issue for me.
