### ISSUE TITLE
[Webpacker] Compilation failed env: node: No such file or directory

### ISSUE THREAD

**Issue by sandergroen** [rails/webpacker#1803]
After upgrading my Rails version from 5.1 to 5.2 and Webpacker from 1.2 to 3.5.5 I have an issue with compiling my js stuff:

[Webpacker] Compiling…
[Webpacker] Compilation failed:
env: node: No such file or directory

I think this has something todo with my local dev environment. At first I had Node version 6 installed om my machine later I installed newer Node versions via NVM and I removed Node version 6. After still having this issue I completely removed all my NVM stuff and reinstalled it.

Can anyone tell me how to get Webpacker to compile?

**Comment by survili** [comment]
@sandergroen did you try creating a new 5.2 app? Maybe it's not related to the upgrade..

**Comment by sandergroen** [comment]
@survili yes I did I'm having the same issue there. I don't think it is related to the upgrade but I do think that it has something todo with my NVM installation. I'm no sure how to make Webpacker work correctly with NVM. It is possible that I need some configuration on the NVM stuff but I don't know.
