### ISSUE TITLE
Documentation on using webpacker with less

### ISSUE THREAD

**Issue by keyboard-clacker** [rails/webpacker#2544]
Is there any documentation on how to use `less-loader` with webpacker? I just spent the last four hours trying to figure out why my application was throwing a `this[MODULE_NAME] is not a function` because of a dependency upgrade, and found out that it was because in my loader I was using `MiniCssExtractPlugin.loader`, but webpacker was using its own internal version of `MiniCssExtractPlugin`. I would like to add to documentation somewhere if possible, this is a very frustrating issue, especially considering mini-css-extract-plugin does not offer an informative error message.

**Comment by joelrojo** [comment]
@keyboard-clacker found this [helpful guide](https://medium.com/@gauravrakheja002/how-to-use-ant-design-dark-mode-in-rails-webpacker-react-8bcae73e9fe). If you take out the ant design config parts, it should work (currently got it working on Rails `5.2.3` and webpacker `5.1.1`).

This issue might also be helpful: #1995

**Comment by keyboard-clacker** [comment]
Nice, missed this when you posted this @joelrojo haha. I think this is still an issue unless it's been documented somewhere or decided that it's not common enough to document officially
