### ISSUE TITLE
Object.entries not available on Node 6

### ISSUE THREAD

**Issue by stevenharman** [rails/webpacker#1021]
I'm trying to use `master` to get the new base config object functionality (from #884), and things were working fine locally. But not when I tried deploying to Heroku. I believe I've traced the issue down to a usage of `Object.entries` in the `environment.js` module. When #884 was merged into `master` it introduced the following line:

https://github.com/rails/webpacker/blob/d6f7be8b8de10bb571b3f5615cfb8aeb1ce74ed3/package/environment.js#L19

I then noticed locally I was running Node `8.3`, but the default Node for the Heroku Ruby build pack is `6.11.1`. Upon upgrading my Heroku Node version to `^8.0.0`, things are working again. Since Webpacker claims to work on Node `6.0.0`, this seems like a bug.

The error on Heroku was:

```text
       Webpacker is installed 🎉 🍰
       Using /tmp/build_d5a48d880470f84bda4a424a5a17b9ab/my-app-web-96e7976d5146d189dc085531dba87635fe06f492/config/webpacker.yml file for setting up webpack paths
       Compiling…
       Compilation failed:
       /tmp/build_d5a48d880470f84bda4a424a5a17b9ab/my-app-web-96e7976d5146d189dc085531dba87635fe06f492/node_modules/@rails/webpacker/package/environment.js:19
       Object.entries(rules).forEach(([key, rule]) => result.set(key, rule))
       ^
       TypeError: Object.entries is not a function
       at getLoaderList (/tmp/build_d5a48d880470f84bda4a424a5a17b9ab/my-app-web-96e7976d5146d189dc085531dba87635fe06f492/node_modules/@rails/webpacker/package/environment.js:19:10)
       at Environment (/tmp/build_d5a48d880470f84bda4a424a5a17b9ab/my-app-web-96e7976d5146d189dc085531dba87635fe06f492/node_modules/@rails/webpacker/package/environment.js:82:20)
       at /tmp/build_d5a48d880470f84bda4a424a5a17b9ab/my-app-web-96e7976d5146d189dc085531dba87635fe06f492/node_modules/@rails/webpacker/package/environments/production.js:7:5
       at createEnvironment (/tmp/build_d5a48d880470f84bda4a424a5a17b9ab/my-app-web-96e7976d5146d189dc085531dba87635fe06f492/node_modules/@rails/webpacker/package/index.js:14:10)
       at Object.<anonymous> (/tmp/build_d5a48d880470f84bda4a424a5a17b9ab/my-app-web-96e7976d5146d189dc085531dba87635fe06f492/node_modules/@rails/webpacker/package/index.js:17:21)
       at Module._compile (module.js:570:32)
       at Object.Module._extensions..js (module.js:579:10)
       at Module.load (module.js:487:32)
       at tryModuleLoad (module.js:446:12)
       at Function.Module._load (module.js:438:3)
 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```

**Comment by gauravtiwari** [comment]
Lets bump up the minimum version requirement to 7.0.0 since node is now at version 10. Thanks for pointing out 👍

**Comment by gauravtiwari** [comment]
Are you happy with the new API's and config?

**Comment by stevenharman** [comment]
> Lets bump up the minimum version requirement to 7.0.0 since node is now at version 10.

That's fine, but it will mean the default `heroku/ruby` built pack will no longer work with Webpacker. Folks will the the non-obvious message above, and then have to tweak their Heroku buildpacks and specify `"node": "^7.0.0"` in their `package.json`.

It's not difficult, per se. But it's also not the "it just works" experience folks are used to.

**Comment by renchap** [comment]
What about having a very simple `Object.entries` polyfill in Webpacker's NPM package, if this is the only thing not supported by Node 6? It only takes 10 lines of JS: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries#Polyfill

This would allow to continue supporting Node 6 for now at a very small cost, and its easy to remove once Node 6 is not used as a default in any major platform. Node 8 is the LTS version since only a few weeks, I think Node 6 still should be supported. And shipping a 10-lines polyfill is not a big thing, especially for a server-side only module (so no impact regarding bundle size).

**Comment by gauravtiwari** [comment]
Yeah, I am going to ditch `entries` and just use `keys` instead.
